### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RandmTask** [xilopaint/alfred-youtube#8]
Love this workflow, it's going to save me so much time!

90% of the time I will want to search by relevance, but the other 10% of the time I want the latest video on something (eg. AI is changing so rapidly). For example typing in ChatGPT, for the first 9 results, 4 will be from a year ago, and 1 from 6 months ago.

![CleanShot 2024-04-29 at 10 04 12](https://github.com/xilopaint/alfred-youtube/assets/7912017/cc74f10d-aec9-4e8f-891b-a2c7d0a0dbe2)

Would be great if we could easily modify the type of search, eg. have an additional keyword character.

eg.
yt - search YouTube with whatever the default is (date/relevance etc)
yt**d** - search YouTube by date
yt**r** - search YouTube by relevance

**Comment by xilopaint** [comment]
I see your point, but I don't think creating new keywords is the right answer to address your need. Alfred should provide a way for developers to allow the change of a setting in a simpler manner without the need to access the configuration window. This is one of the many limitations of Alfred that made me switch to Raycast. The YouTube extension for Raycast allows you to do exactly that through a dropdown:

<img width="886" alt="Screenshot 2024-04-29 at 10 21 56" src="https://github.com/xilopaint/alfred-youtube/assets/11052366/959db1fa-369c-4026-840a-0ba247acec28">
