### ISSUE TITLE
Suggestion regarding copying links

### ISSUE THREAD

**Issue by RandmTask** [xilopaint/alfred-youtube#9]
When copying one of the links from the results presented in Alfred, (By selecting the results and pressing Command+C) it copies the URL only.

Would it be possible to have an **option** to copy the URL **and** title, so when you paste it somewhere it pastes like this (with the title as the hyperlink):

[Testing If You Can Blow Your Own Sail - YouTube](https://www.youtube.com/watch?v=M7-h3FO-KKo&ab_channel=MarkRober)

Instead of this:

https://www.youtube.com/watch?v=M7-h3FO-KKo

Thanks!

**Comment by xilopaint** [comment]
I can't see how this would work without the target application supporting markdown.
